
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khtzffbnwkcehkdijqll.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtodHpmZmJud2tjZWhrZGlqcWxsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4OTkyMTUsImV4cCI6MjA1NzQ3NTIxNX0.hwd2O4iD-BewKiTxCJIqA77FHJGLG4VFEZ-T2xBl3Tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
